# JEDI and server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-configmap
data:
  panda_server_configmap.json: |-
{{ .Files.Get "panda_server_configmap.json" | indent 4}}

{{- if .Values.hostcerts.enabled -}}
---
# host cert and key
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "server.fullname" . }}-certs
data:
    hostcert.pem: |-
{{ .Files.Get "hostcert.pem" | indent 8}}

    hostkey.pem: |-
{{ .Files.Get "hostkey.pem" | indent 8}}
{{- end }}
