# server configuration json
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-configjson
data:
  panda_server_config.json: |-
{{ .Files.Get "panda_server_config.json" | indent 4}}

---
# server env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-env
data:
  {{- if .Values.httpProxy }}
  http_proxy: "{{ .Values.httpProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost,{{ include "server.fullname" . }}"
  {{- end }}
  {{- if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpProxy }}"
  {{- end }}
  {{- else if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpsProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost,{{ include "server.fullname" . }}"
  {{- end }}
  {{- end }}
  {{- if .Values.noRoot }}
  PANDA_NO_ROOT: "1"
  {{- end }}

---
# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-sandbox
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}
