{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "server.fullname" . }}-route
  labels:
      {{- include "server.labels" . | nindent 4 }}

spec:
  host: {{ .Values.route.hostName}}
  to:
    kind: Service
    name: {{ include "server.fullname" . }}
  port:
    targetPort: {{ .Values.service.httpsPort }}
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}