# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-configmap
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  PANDA_DB_PASSWORD: {{ .Values.database.password }}
  {{- if .Values.database.panda_dbhost }}
  PANDA_DB_HOST: {{ .Values.database.dbhost }}
  {{- else }}
  PANDA_DB_HOST: {{ include "postgres.fullname" . }}
  {{- end }}
