# Default values for iam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


organization: &organization Rubin
secret_enabled: &secret_enabled true

main:
  enabled: true

  secret:
    enabled: *secret_enabled
    name: "iam-dev-secret"

  iam:
    organization: *organization

mariadb:
  enabled: true

  iam:
    organization: *organization

  secret:
    enabled: *secret_enabled
    name: "iam-dev-secret"
