# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-configmap
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  {{- if .Values.noRoot }}
  PGDATA: "/tmp/pg_volume/data"
  {{- end }}

