apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: activemq-port
      protocol: TCP
      name: activemq-port
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}
