# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-db-envs
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.database.name }}"
  POSTGRES_USER: "{{ .Values.database.user }}"
  POSTGRES_PASSWORD: "{{ .Values.database.password }}"
  POSTGRES_SCHEMA: "{{ .Values.database.schema }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-envs
type: Opaque
stringData:
  {{- if .Values.panda.authIdToken }}
  PANDA_AUTH_ID_TOKEN: "{{ .Values.panda.authIdToken }}"
  PANDA_AUTH_VO: "{{ .Values.panda.authVO }}"
  PANDA_AUTH: "{{ .Values.panda.auth }}"
  {{- end }}
  {{- if .Values.panda.behindRealLB }}
  PANDA_BEHIND_REAL_LB: "1"
  {{- end }}

  IDDS_DATABASE_NAME: "{{ .Values.database.name}}"
  IDDS_DATABASE_USER: "{{ .Values.database.user}}"
  IDDS_DATABASE_PASSWORD: "{{ .Values.database.password}}"
  IDDS_DATABASE_SCHEMA: "{{ .Values.database.schema}}"
  IDDS_DATABASE_HOST: "{{ .Values.database.host}}"

  IDDS_CONDUCTOR_BROKERS: "{{.Values.conductor.brokers}}"
  IDDS_CONDUCTOR_PORT: "{{.Values.conductor.port}}"
  IDDS_CONDUCTOR_DESTINATION: "{{.Values.conductor.destination}}"
  IDDS_CONDUCTOR_USERNAME: "{{.Values.conductor.username}}"
  IDDS_CONDUCTOR_PASSWORD: "{{.Values.conductor.password}}"

  IDDS_OIDC_RUBIN_CLIENT_ID: "{{.Values.oidc.rubin.client_id}}"
  IDDS_OIDC_RUBIN_CLIENT_SECRET: "{{.Values.oidc.rubin.client_secret}}"
  IDDS_OIDC_RUBIN_PRODUCTION_CLIENT_ID: "{{.Values.oidc.rubin_production.client_id}}"
  IDDS_OIDC_RUBIN_PRODUCTION_CLIENT_SECRET: "{{.Values.oidc.rubin_production.client_secret}}"
  IDDS_OIDC_PANDA_DEV_CLIENT_ID: "{{.Values.oidc.panda_dev.client_id}}"
  IDDS_OIDC_PANDA_DEV_CLIENT_SECRET: "{{.Values.oidc.panda_dev.client_secret}}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-certs
type: Opaque
stringData:
  hostcert.pem: |-
{{ .Files.Get "hostcert.pem" | indent 4}}

  hostkey.pem: |-
{{ .Files.Get "hostkey.pem" | indent 4}}
