{{- if .Values.harvester.enabled }}
# harvester configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-envs
type: Opaque
stringData:
  MARIADB_DATABASE: "harvester"
  MARIADB_USER: "harvester"
  MARIADB_PASSWORD: {{ .Values.harvester.database.password }}
  MARIADB_ROOT_PASSWORD: {{ .Values.harvester.database.admin_password }}
  {{- if .Values.harvester.database.dbhost }}
  HARVESTER_DB_HOST: {{ .Values.harvester.database.dbhost }}
  {{- else }}
  HARVESTER_DB_HOST: "{{ include "add_affix" (list .Values.affix "harvester") }}-mariadb"
  {{- end }}

  PANDA_AUTH_ID_TOKEN: {{ .Values.auth.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.auth.authVO }}
  PANDA_BEHIND_REAL_LB: "1"
  {{- if .Values.panda.url }}
  PANDA_URL: "{{ .Values.panda.url}}"
  {{- else }}
  PANDA_URL: "http://{{ include "add_affix" (list .Values.affix "panda") }}-server:{{ .Values.panda.port }}/server/panda"
  {{- end }}
  {{- if .Values.panda.urlSSL }}
  PANDA_URL_SSL: "{{ .Values.panda.urlSSL }}"
  {{- else }}
  PANDA_URL_SSL: "https://{{ include "add_affix" (list .Values.affix "panda") }}-server:{{ .Values.panda.sslPort }}/server/panda"
  {{- end }}

  {{- if .Values.harvester.experiment }}
  EXPERIMENT: {{ .Values.harvester.experiment }}
  {{- end}}

  HARVESTER_ID: "{{ .Values.harvester.harvesterID }}"
  {{ if .Values.harvester.useStableCondor }}
  CONDOR_CHANNEL: ".stable"
  {{- end }}

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/harvester_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- end }}
