{{- if .Values.idds.enabled }}
# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idds.name }}-db-envs
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.idds.database.name }}"
  POSTGRES_USER: "{{ .Values.idds.database.user }}"
  POSTGRES_PASSWORD: "{{ .Values.idds.database.password }}"
  POSTGRES_SCHEMA: "{{ .Values.idds.database.schema }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idds.name }}-envs
type: Opaque
stringData:
  PANDA_AUTH_ID_TOKEN: "{{ .Values.auth.authIdToken }}"
  PANDA_AUTH_VO: "{{ .Values.auth.authVO }}"
  PANDA_AUTH: "{{ .Values.auth.auth }}"

  IDDS_DATABASE_NAME: "{{ .Values.idds.database.name}}"
  IDDS_DATABASE_USER: "{{ .Values.idds.database.user}}"
  IDDS_DATABASE_PASSWORD: "{{ .Values.idds.database.password}}"
  IDDS_DATABASE_SCHEMA: "{{ .Values.idds.database.schema}}"
  IDDS_DATABASE_HOST: "{{ .Values.idds.database.host}}"

  IDDS_CONDUCTOR_BROKERS: "{{ join "," .Values.msgsvc.serverList }}"
  IDDS_CONDUCTOR_PORT: "{{default "61613" .Values.msgsvc.port }}"
  IDDS_CONDUCTOR_DESTINATION: "{{.Values.idds.msgsvc.destination}}"
  IDDS_CONDUCTOR_USERNAME: "{{.Values.idds.msgsvc.username}}"
  IDDS_CONDUCTOR_PASSWORD: "{{.Values.msgsvc.basePasswd}}_{{.Values.idds.msgsvc.username}}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idds.name }}-auth
type: Opaque
stringData:
  "auth.cfg": |-
     {"common":
         {"allow_vos": ""
         }
     }
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idds.name }}-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/idds_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- end }}
