
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  # note the name is the DB services/pods  not the Cluster name.
  name: usdf-panda-server
spec:
  startDelay: 300
  backup:
    retentionPolicy: "15d"
    barmanObjectStore:
      destinationPath: s3://rubin-panda-dev
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
  instances: 2
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: panda
      owner: rubin
      secret:
        name: usdf-panda-server-creds
  
  imageName:  ghcr.io/pandawms/panda-k8s:0.0.1
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    shared_preload_libraries: [ 'pg_cron', 'pg_partman_bgw' ]
    parameters:
      shared_buffers: 16GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    pg_hba:
      - local all panda trust
      - host all panda localhost trust
      - local all postgres trust
      - host all postgres localhost trust
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5
      - host all postgres 0.0.0.0/0 reject
      - host all postgres ::0/0 reject

  resources:
    requests:
      memory: 64Gi
      cpu: 16
    limits:
      memory: 128Gi
      cpu: 32 

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi


