# Default values for activemq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


daemon:
  enabled: true
  image:
    tag: "5.14.3"

  persistentvolume:
    class: default

  # to create topics and queues
  topics: "iddspanda;pandaidds"
  queues: "iddspanda;pandaidds"

  # define the user and password
  admin:
    name: admin
    password: MyActiveMQPass0508
  user:
    name: idds
    password: MyPass0508
  owner:
    name: iddsowner
    password: MyPass0508
  read:
    name: iddsread
    password: MyPass0508
  write:
    name: iddswrite
    password: MyPass0508
