---
# Source: bigmon/charts/main/templates/configmap.yaml
# JEDI and server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: bigmon-dev-main-configmap
binaryData:
  00-httpd.conf.template: |-
    U2VydmVyTmFtZSAke0JJR01PTl9IT1NUfQo=
  local.py.template: |-
    IyBEYXRhYmFzZSBzZXR0aW5ncwojIE1ha2UgdGhpcyB1bmlxdWUsIGFuZCBkb24ndCBzaGFyZSBpdCB3aXRoIGFueWJvZHkuCk1ZX1NFQ1JFVF9LRVkgPSAnJHtCSUdNT05fU0VDUkVUX0tFWX0nCgpkYmFjY2Vzc19wb3N0Z3JlcyA9IHsKICAgICAgICAgJ2RlZmF1bHQnOgogICAgICAgICB7CiAgICAgICAgICdFTkdJTkUnOidkamFuZ28uZGIuYmFja2VuZHMucG9zdGdyZXNxbF9wc3ljb3BnMicsCiAgICAgICAgICdPUFRJT05TJzogewogICAgICAgICAgICAgICAgICdvcHRpb25zJzogJy1jIHNlYXJjaF9wYXRoPWRvbWFfcGFuZGFiaWdtb24sZG9tYV9wYW5kYW1ldGEsZG9tYV9wYW5kYSxkb21hX3BhbmRhYXJjaCxwdWJsaWMnCiAgICAgICAgIH0sCiAgICAgICAgICdOQU1FJzogJyR7UEFOREFfREJfTkFNRX0nLAogICAgICAgICAnSE9TVCc6ICcke1BBTkRBX0RCX0hPU1R9JywKICAgICAgICAgJ1BPUlQnOiAnJHtQQU5EQV9EQl9QT1JUfScsCiAgICAgICAgICdVU0VSJzogJyR7UEFOREFfREJfVVNFUn0nLAogICAgICAgICAnUEFTU1dPUkQnOiAiJHtQQU5EQV9EQl9QQVNTV09SRH0iLAogICAgICAgICB9LAogICAgICAgICdkb21hX2lkZHNfZ2NwJzoKICAgICAgICB7CiAgICAgICAgJ0VOR0lORSc6J2RqYW5nby5kYi5iYWNrZW5kcy5wb3N0Z3Jlc3FsX3BzeWNvcGcyJywKICAgICAgICAnT1BUSU9OUyc6IHsKICAgICAgICAgICAgICAgICAnb3B0aW9ucyc6ICctYyBzZWFyY2hfcGF0aD1kb21hX2lkZHMscHVibGljJwogICAgICAgIH0sCiAgICAgICAgJ05BTUUnOiAnJHtJRERTX0RCX05BTUV9JywKICAgICAgICAnSE9TVCc6ICcke0lERFNfREJfSE9TVH0nLAogICAgICAgICdQT1JUJzogJyR7SUREU19EQl9QT1JUfScsCiAgICAgICAgJ1VTRVInOiAnJHtJRERTX0RCX1VTRVJ9JywKICAgICAgICAnUEFTU1dPUkQnOiAiJHtJRERTX0RCX1BBU1NXT1JEfSIsCiAgICAgICAgIH0sICAgICAgICAKfQoKZGJhY2Nlc3MgPSBkYmFjY2Vzc19wb3N0Z3JlcwoKI2F3cwphd3MgPSB7CiAgICAiQVdTX0FDQ0VTU19LRVlfQVRMQVMiIDogIiR7QVdTX0FDQ0VTU19LRVlfQVRMQVN9IiwKICAgICJBV1NfU0VDUkVUX0tFWV9BVExBUyIgOiAiJHtBV1NfU0VDUkVUX0tFWV9BVExBU30iCn0KCgpTRVNTSU9OX0NPT0tJRV9TQU1FU0lURSA9IE5vbmUKU09DSUFMX0FVVEhfUkVESVJFQ1RfSVNfSFRUUFMgPSBGYWxzZQpTRVNTSU9OX0NPT0tJRV9TRUNVUkU9RmFsc2UKCiMgc2V0IGRlZmF1bHQgZGF0ZXRpbWUgZm9ybWF0IGZvciBkYXRldGltZS5kYXRldGltZS5zdHJmdGltZSgpCmRlZmF1bHREYXRldGltZUZvcm1hdE15U1FMID0gIiVZLSVtLSVkICVIOiVNOiVTWiIKZGVmYXVsdERhdGV0aW1lRm9ybWF0T3JhY2xlID0gIiVZLSVtLSVkICVIOiVNOiVTIgpkZWZhdWx0RGF0ZXRpbWVGb3JtYXQgPSBkZWZhdWx0RGF0ZXRpbWVGb3JtYXRPcmFjbGUKCgpGSUxFQlJPV1NFUl9ESVJFQ1RPUlkgPSAiZmlsZWJyb3dzZXIiClJVQ0lPX0FDQ09VTlQgPSAiJHtSVUNJT19BQ0NPVU5UfSIKQ0FQQVRIID0gIi9ldGMvZ3JpZC1zZWN1cml0eS9jZXJ0aWZpY2F0ZXMiClJVQ0lPX1JFRElSRUNUX0hPU1QgPSAiJHtSVUNJT19TRVJWRVJfSE9TVH0iClJVQ0lPX0FVVEhfSE9TVCA9ICIke1JVQ0lPX0FVVEhfSE9TVH0iClJVQ0lPX1NFUlZFUl9IT1NUID0gIiR7UlVDSU9fU0VSVkVSX0hPU1R9IgpNRURJQV9VUkwgPSAnL21lZGlhLycKCgojIGxvZyBkaXJlY3RvcnkKTE9HX1JPT1QgPSAiL2RhdGEvYmlnbW9uL2xvZ3MiCkRFQlVHID0gIiR7QklHTU9OX0RFQlVHfSIgPT0gJ1RydWUnCiNVU0VfVFogPSBUcnVlClVTRV9UWiA9IEZhbHNlClBST0RTWVMgPSB7CiJwcm9kc3lzSG9zdCI6ICdwcm9kdGFzay1kZXYuY2Vybi5jaCcsCiJwcm9kc3lzVG9rZW4iOiAiJHtQUk9EU1lTX1RPS0VOfSIsCiJwcm9kc3lzVXJsIjogJy9wcm9kdGFzay90YXNrX2FjdGlvbl9leHQvZmluaXNoLycsCn0KRVMgPSB7CiJlc0hvc3QiOidlcy1hdGxhcy5jZXJuLmNoJywKImVzUG9ydCI6JzkyMDMnLAoiZXNVc2VyIjonJHtFU19VU0VSfScsCiJlc1Bhc3N3b3JkIjonJHtFU19QQVNTV09SRH0nLAp9CgpTT0NJQUxfQVVUSF9HT09HTEVfT0FVVEgyX0tFWSA9ICIke1NPQ0lBTF9BVVRIX0dPT0dMRV9PQVVUSDJfS0VZfSIKU09DSUFMX0FVVEhfR09PR0xFX09BVVRIMl9TRUNSRVQgPSAiJHtTT0NJQUxfQVVUSF9HT09HTEVfT0FVVEgyX1NFQ1JFVH0iCgpTT0NJQUxfQVVUSF9DRVJOT0lEQ19LRVkgPSAnJHtTT0NJQUxfQVVUSF9DRVJOT0lEQ19LRVl9JwpTT0NJQUxfQVVUSF9DRVJOT0lEQ19TRUNSRVQgPSAnJHtTT0NJQUxfQVVUSF9DRVJOT0lEQ19TRUNSRVR9JwoKU09DSUFMX0FVVEhfR0lUSFVCX0tFWSA9ICcke1NPQ0lBTF9BVVRIX0dJVEhVQl9LRVl9JwpTT0NJQUxfQVVUSF9HSVRIVUJfU0VDUkVUID0gJyR7U09DSUFMX0FVVEhfR0lUSFVCX1NFQ1JFVH0nCgpTT0NJQUxfQVVUSF9JTkRJR09JQU1fS0VZID0gJyR7U09DSUFMX0FVVEhfSU5ESUdPSUFNT0lEQ19LRVl9JwpTT0NJQUxfQVVUSF9JTkRJR09JQU1fU0VDUkVUID0gJyR7U09DSUFMX0FVVEhfSU5ESUdPSUFNT0lEQ19TRUNSRVR9JwpTT0NJQUxfQVVUSF9JTkRJR09JQU1fQkFTRVBBVEggPSAnJHtTT0NJQUxfQVVUSF9JTkRJR09JQU1PSURDX0JBU0VQQVRIfScKCkVNQUlMX0hPU1QgPSAic210cC5jZXJuLmNoIgpFTUFJTF9QT1JUID0gNTg3CkVNQUlMX0hPU1RfVVNFUiA9ICIke0VNQUlMX0hPU1RfVVNFUn0iCkVNQUlMX0hPU1RfUEFTU1dPUkQgPSAiJHtFTUFJTF9IT1NUX1BBU1NXT1JEfTgiCkVNQUlMX1VTRV9UTFMgPSBUcnVlCkdSQUZBTkEgPSB7CiAgICAiQXV0aG9yaXphdGlvbiI6ICJCZWFyZXIgJHtHUkFGQU5BX0FVVEhfVE9LRU59IgogICB9Ck9DX1RPS0VOID0gIiR7T0NfVE9LRU59IgpPQ19FTkRQT0lOVCA9ICJvcGVuc2hpZnQuY2Vybi5jaCIKT0NfTkFNRVNQQUNFID0gImJpZ3BhbmRhLW1sZmxvdyIKCg==
  process_template.py: |-
    aW1wb3J0IG9zCmltcG9ydCByZQppbXBvcnQgZ2xvYgoKIyBsb29wIG92ZXIgYWxsIHRlbXBsYXRlIGZpbGVzCnNhbmRib3hfZGlyID0gb3MucGF0aC5hYnNwYXRoKG9zLnBhdGguZGlybmFtZShfX2ZpbGVfXykpCmZvciBuYW1lIGluIGdsb2IuZ2xvYihvcy5wYXRoLmpvaW4oc2FuZGJveF9kaXIsICcqLnRlbXBsYXRlJykpOgogICAgbmV3X2ZpbGVuYW1lID0gcmUuc3ViKCdcLnRlbXBsYXRlJCcsICcnLCBuYW1lKQogICAgIyBwYXRjaAogICAgd2l0aCBvcGVuKG5hbWUpIGFzIGY6CiAgICAgICAgdGVtcGxhdGUgPSBmLnJlYWQoKQogICAgICAgICMgcmVwbGFjZSBwbGFjZWhvbGRlcnMgd2l0aCBlbnYgdmFycwogICAgICAgIGl0ZW1zID0gcmUuZmluZGFsbChyJ1wkXHsoXHcrKVx9JywgdGVtcGxhdGUpCiAgICAgICAgZG9uZV9saXN0ID0gc2V0KCkKICAgICAgICBmb3IgaXRlbSBpbiBpdGVtczoKICAgICAgICAgICAgaWYgaXRlbSBpbiBkb25lX2xpc3Q6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICBkb25lX2xpc3QuYWRkKGl0ZW0pCiAgICAgICAgICAgIGlmIGl0ZW0gaW4gb3MuZW52aXJvbjoKICAgICAgICAgICAgICAgIHRlbXBsYXRlID0gdGVtcGxhdGUucmVwbGFjZSgnJHsnK2l0ZW0rJ30nLCBvcy5lbnZpcm9uW2l0ZW1dKQogICAgIyBkdW1wCiAgICB3aXRoIG9wZW4obmV3X2ZpbGVuYW1lLCAndycpIGFzIGY6CiAgICAgICAgZi53cml0ZSh0ZW1wbGF0ZSkK
---
# Source: bigmon/charts/main/templates/configmap.yaml
# env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: bigmon-dev-main-env
data:
  # bigmon
  BIGMON_HOST: "FIXME"
  BIGMON_NUM_WSGI_PROC: "10"
  BIGMON_SECRET_KEY: "FIXME"
  BIGMON_VO: "FIXME"
  BIGMON_DEPLOYMENT: "POSTGRES"
  BIGMON_DEBUG: "False"
  # Auth
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "FIXME"
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "FIXME"
  SOCIAL_AUTH_CERNOIDC_KEY: "FIXME"
  SOCIAL_AUTH_CERNOIDC_SECRET: "FIXME"
  SOCIAL_AUTH_GITHUB_KEY: "FIXME"
  SOCIAL_AUTH_GITHUB_SECRET: "FIXME"
  SOCIAL_AUTH_INDIGOIAMOIDC_KEY: "FIXME"
  SOCIAL_AUTH_INDIGOIAMOIDC_SECRET: "FIXME"
  SOCIAL_AUTH_INDIGOIAMOIDC_BASEPATH: "FIXME"
  # PandaDB
  PANDA_DB_NAME: "panda_db"
  PANDA_DB_HOST: "panda-postgres"
  PANDA_DB_PORT: "5432"
  PANDA_DB_USER: "panda"
  PANDA_DB_PASSWORD: "FIXME"
  # iDDSDB
  IDDS_DB_NAME: ""
  IDDS_DB_HOST: "idds-postgres"
  IDDS_DB_PORT: ""
  IDDS_DB_USER: ""
  IDDS_DB_PASSWORD: "FIXME"
  # Rucio
  RUCIO_SERVER_HOST: "https://rucio-lb-prod.cern.ch"
  RUCIO_AUTH_HOST: "https://rucio-auth-prod.cern.ch"
  RUCIO_ACCOUNT: "iddsv1"
  # CRIC
  CRIC_API_URL: "https://datalake-cric.cern.ch/api/atlas/pandaqueue/query/?json"
  # iDDS
  IDDS_HOST: "https://idds-rest:443/idds"
  # AWS
  AWS_ACCESS_KEY_ATLAS: "FIXME"
  AWS_SECRET_KEY_ATLAS: "FIXME"

  # HTTP proxy
---
# Source: bigmon/charts/main/templates/deployment.yaml
# pv
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bigmon-dev-main
  labels:
    helm.sh/chart: main-0.1.0
    app.kubernetes.io/name: main
    app.kubernetes.io/instance: bigmon-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: wekafs--sdf-k8s01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# Source: bigmon/charts/main/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bigmon-dev-main
  labels:
    helm.sh/chart: main-0.1.0
    app.kubernetes.io/name: main
    app.kubernetes.io/instance: bigmon-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: main
    app.kubernetes.io/instance: bigmon-dev
---
# Source: bigmon/charts/main/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigmon-dev-main
  labels:
    helm.sh/chart: main-0.1.0
    app.kubernetes.io/name: main
    app.kubernetes.io/instance: bigmon-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: main
      app.kubernetes.io/instance: bigmon-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: main
        app.kubernetes.io/instance: bigmon-dev
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: main
          securityContext:
            {}
          image: "ghcr.io/pandawms/panda-bigmon-core:v0.3.0"
          imagePullPolicy: IfNotPresent

          command: ["/bin/sh", "-c"]
          args:
            - cp /data/bigmon/configmap/* /data/bigmon/config/ ;
              python /data/bigmon/config/process_template.py ;
              until /usr/pgsql-*/bin/pg_isready -h ${PANDA_DB_HOST} -p ${PANDA_DB_PORT}; do echo waiting for database; sleep 2; done;
              start-daemon.sh all
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {}
          volumeMounts:
              - name: bigmon-dev-main-logs
                mountPath: /data/bigmon/logs
              - name: bigmon-dev-main-configmap
                mountPath: /data/bigmon/configmap
          envFrom:
            - configMapRef:
                name: bigmon-dev-main-env
      volumes:
        - name: bigmon-dev-main-logs
          persistentVolumeClaim:
            claimName: bigmon-dev-main
        - name: bigmon-dev-main-configmap
          configMap:
              name: bigmon-dev-main-configmap
---
# Source: bigmon/charts/main/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bigmon-dev-main
  labels:
    helm.sh/chart: main-0.1.0
    app.kubernetes.io/name: main
    app.kubernetes.io/instance: bigmon-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: optional
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "bigmon-dev-main.slac.stanford.edu"
      secretName: 
  rules:
    - host: "bigmon-dev-main.slac.stanford.edu"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bigmon-dev-main
                port:
                  number: 443
