# Default values for iam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"

main:
  enabled: true

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: panda-iam-dev.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: cern.ch
            hostOverride: panda-iam-dev.cern.ch

mariadb:
  enabled: true

