# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-external-sandbox
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}
