# iDDS configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest.fullname" . }}-configmap
data:
  idds_configmap.json: |-
{{ .Files.Get "idds_configmap.json" | indent 8}}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest.fullname" . }}-envs
data:
  {{- if .Values.httpProxy }}
  http_proxy: "{{ .Values.httpProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else}}
  no_proxy: "localhost,{{ include "rest.fullname" . }},{{ .Release.Name }}-daemon,{{ .Release.Name }}-postgres"
  {{- end}}
  {{- if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpProxy }}"
  {{- end }}
  {{- else if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpsProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else}}
  no_proxy: "localhost,{{ include "rest.fullname" . }},{{ .Release.Name }}-daemon,{{ .Release.Name }}-postgres"
  {{- end}}
  {{- end }}


---
# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest.fullname" . }}-sandbox
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}
