# Default values for bigmon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

main:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/pandawms/panda-bigmon-core
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  autoStart: true

  #persistentvolume:
  #  create: false         
  #  path: "/mnt/panda-bigmon-logs"
  #  size: 5Gi
  hostcerts:
    enabled: false

  # hostname for external access
  hostName: "FIXME"

  # secret key for configuration
  secretKey: "FIXME"

  database:
    hostName: "panda-postgres"
    password: "FIXME"

  rucio:
    rucioHost: "https://rucio-lb-prod.cern.ch"
    authHost: "https://rucio-auth-prod.cern.ch"

  service:
    type: ClusterIP
    httpsPort: 443

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        # hostOverride: panda-k8s-dev-jedi.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: cern.ch
            # hostOverride: panda-k8s-dev-jedi.cern.ch

  # use Route class to expose the service
  route:
    enabled: false
