# Default values for bigmon.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.
#

main:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false

  ingress:
    enabled: true
    hosts:
      - domain: slac.stanford.edu
        # hostOverride: panda-k8s-dev-jedi.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: slac.stanford.edu
