# JEDI and server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-configmap
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- if .Values.hostcerts.enabled -}}
---
# host cert and key
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "main.fullname" . }}-certs
data:
    hostcert.pem: |-
{{ .Files.Get "hostcert.pem" | indent 8}}

    hostkey.pem: |-
{{ .Files.Get "hostkey.pem" | indent 8}}
{{- end }}

---
# env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-env
data:
  # bigmon
  BIGMON_HOST: "{{ .Values.hostName }}"
  MY_SECRET_KEY: "{{ .Values.secretKey }}"
  BIGMON_NUM_WSGI_PROC: "{{ .Values.httpd.numWSGI }}"
  # PandaDB
  PANDA_DB_NAME: "{{ .Values.database.databaseName }}"
  PANDA_DB_HOST: "{{ .Values.database.hostName }}"
  PANDA_DB_PORT: "{{ .Values.database.port }}"
  PANDA_DB_USER: "{{ .Values.database.userName }}"
  PANDA_DB_PASSWORD: "{{ .Values.database.password }}"
  # Rucio
  RUCIO_SERVER_HOST: "{{ .Values.rucio.rucioHost }}"
  RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"
