# JEDI and server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-configmap
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- if .Values.hostcerts.enabled }}
---
# host cert and key
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-certs
binaryData:
  hostcert.pem: |-
    {{ .Files.Get "cert/hostcert.pem" | b64enc }}
  hostkey.pem: |-
    {{ .Files.Get "cert/hostkey.pem" | b64enc }}
{{- end }}

---
# env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-env
data:
  # bigmon
  BIGMON_HOST: "{{ .Values.hostName }}"
  BIGMON_NUM_WSGI_PROC: "{{ .Values.httpd.numWSGI }}"
  MY_SECRET_KEY: "{{ .Values.secretKey }}"
  # PandaDB
  PANDA_DB_NAME: "{{ .Values.database.databaseName }}"
  PANDA_DB_HOST: "{{ .Values.database.hostName }}"
  PANDA_DB_PORT: "{{ .Values.database.port }}"
  PANDA_DB_USER: "{{ .Values.database.userName }}"
  PANDA_DB_PASSWORD: "{{ .Values.database.password }}"
  # Rucio
  RUCIO_SERVER_HOST: "{{ .Values.rucio.rucioHost }}"
  RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"
  # proxy
  {{- if .Values.httpProxy }}
  http_proxy: "{{ .Values.httpProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost"
  {{- end }}
  {{- if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpProxy }}"
  {{- end }}
  {{- else if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpsProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost"
  {{- end }}
  {{- end }}
