# harvester configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-configjson
data:
  panda_harvester_configmap.json: |-
{{ .Files.Get "panda_harvester_configmap.json" | indent 4}}
---
# queue config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-queueconfig
data:
  {{- if .Values.experiment }}
  {{ $pq_file :=  printf "%s.%s" .Values.experiment "panda_queueconfig.json" }}
  panda_queueconfig.json: |-
{{ .Files.Get $pq_file | indent 4}}
  {{- else}}
  panda_queueconfig.json: |-
{{ .Files.Get "panda_queueconfig.json" | indent 4}}
  {{- end}}

  pilot_wrapper.sh: |-
{{ .Files.Get "pilot_wrapper.sh" | indent 4}}
---
# env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-env
data:
  {{- if .Values.httpProxy }}
  http_proxy: "{{ .Values.httpProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }},{{ .Values.panda.host }}"
  {{- else }}
  no_proxy: "localhost,{{ include "harvester.fullname" . }},{{ .Values.panda.host }}"
  {{- end }}
  {{- if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpProxy }}"
  {{- end }}
  {{- else if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpsProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }},{{ .Values.panda.host }},http-{{ .Values.panda.host }}"
  {{- else }}
  no_proxy: "localhost,{{ include "harvester.fullname" . }},{{ .Values.panda.host }},http-{{ .Values.panda.host }}"
  {{- end }}
  {{- end }}

---
# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-sandbox
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

