{{- if .Values.route.enabled -}}
# for log access
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "harvester.fullname" . }}-route
  labels:
      {{- include "harvester.labels" . | nindent 4 }}
  {{- if .Values.global.deploymentName }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  {{- end }}

spec:
  host: {{ .Values.route.hostName }}
  {{- if .Values.global.deploymentName }}
  path: "/{{ .Values.global.deploymentName }}"
  {{- end }}
  to:
    kind: Service
    {{- if .Values.global.deploymentName }}
    name: "{{ .Values.global.deploymentName }}"
    {{- else }}
    name: {{ include "harvester.fullname" . }}
    {{- end }}
  port:
    targetPort: http
{{ end }}
