{{- if .Values.route.enabled -}}
# for log access
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "harvester.fullname" . }}-route
  labels:
      {{- include "harvester.labels" . | nindent 4 }}

spec:
  host: {{ .Values.route.hostName }}
  to:
    kind: Service
    {{- if .Values.global.deploymentName }}
    name: "{{ .Values.global.deploymentName }}-harvester"
    path: "/{{ .Values.global.deploymentName }}-harvester"
    {{- else }}
    name: {{ include "harvester.fullname" . }}
    {{- end }}
  port:
    targetPort: http
{{ end }}
