# Default values for bigmon.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.
#

main:
  persistentvolume:
    create: true

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: panda-bigmon-dev.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: cern.ch
            hostOverride: panda-bigmon-dev.cern.ch
