# JEDI and server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jedi.fullname" . }}-configmap
data:
  panda_jedi_configmap.json: |-
{{ .Files.Get "panda_jedi_configmap.json" | indent 4}}
