apiVersion: v1
kind: Service
metadata:
  name: {{ include "jedi.fullname" . }}
  labels:
    {{- include "jedi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jedi.selectorLabels" . | nindent 4 }}
