# secret main file

# global values
auth:
  auth: "oidc"
  authIdToken: "FIXME"
  authVO: "panda_dev"

  oidc:
    audience: "https://pandaserver-doma.cern.ch"
    config_url: "https://panda-iam-doma.cern.ch/.well-known/openid-configuration"
    clients:
      - name: "panda_dev"
        client_id: "FIXME"
        client_secret: "FIXME"
      - name: "Rubin"
        client_id: "FIXME"
        client_secret: "FIXME"
      - name: "Rubin.production"
        client_id: "FIXME"
        client_secret: "FIXME"


msgsvc:
  enabled: true
  name: "msgsvc-secret"

  serverList:
    - "activemq-dev:61613"

  basePasswd: "FIXME"


panda:
  enabled: true
  name: "panda-secret"

  database:
    password: "FIXME"
    dbhost: "FIXME"


harvester:
  enabled: true
  name: "harvester-secret"

  database:
    password: FIXME
    admin_password: FIXME
    dbhost: "FIXME"


idds:
  enabled: true
  name: "idds-secret"

  restHost: "idds-rest"
  restPort: 8443

  database:
    name: "idds_db"
    user: "idds"
    password: "MyPass123"
    schema: "doma_idds"
    host: "idds-dev-postgres"

  msgsvc:
    detination: /queue/idds_panda
    username: idds


bigmon:
  enabled: true
  name: "bigmon-secret"


iam:
  enabled: true
  name: "iam-secret"

  database:
    host: "iam-mariadb"
    name: "iam_db"
    user: "iam"
    password: "MyPass0508"
    admin_password: "MyAdminPass0508"

  cilogon:
    client_id: "FIXME"
    client_secret: "FIXME"


rucio:
  rucioHost: "sprucio01.sdcc.bnl.gov:443"
  authHost: "sprucio01.sdcc.bnl.gov:443"
  username: "iddsv1"
  password: "FIXME"
  account: "iddsv1"
