# Default values for messaging service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

activemq:
  # enable 
  enabled: true

  # container image and tag
  image:
    tag: "0.0.3"
    # tag: "main"

  # PV with selector support
  #persistentvolume:
  #    selector: false
